from docparts import doc_parts, section_parts, problem, exam_parts
from algebra import make_quadratic_eq, make_linear_eq, make_rational_poly_simplify
from calc1 import make_poly_ratio_limit, make_chain_rule_prob, make_quotient_rule_prob
from calc1 import make_horizontal_tangents, make_find_derivative_at_value